### ISSUE TITLE
[BUG] login in vscode pluin

### ISSUE THREAD

**Issue by wanghui5257** [Monica-IM/Monica-Code#11]
## Environment
- IDE: Visual Studio Code

- IDE Version: Version: 1.95.3 (Universal)

- Monica Code Version: 插件 v1.1.22
- Operating System: 
macOS 15.1  m2
## Steps to Reproduce
1. 
在vs code插件登陆报错，报错信息见截图
![image](https://github.com/user-attachments/assets/a2a7417f-afc0-4794-a097-b26879316741)
![image](https://github.com/user-attachments/assets/d8db47cf-572c-4817-a1df-a596251c36c2)

以前可以登陆，今天不行了

**Comment by MMMartt** [comment]
The issue lies in the additional configuration you included in the "proxy" settings within "requestOptions." It seems that null values are not being ignored, which will be addressed in the next version. This is also the reason for JetBrains' network connectivity problems. Please double-check your setup in the meantime. If you need to set up a proxy, make sure the entire field is as follows:  
```json
"requestOptions": {
  "proxy": "http://127.0.0.1:7890"
}
```  
Avoid adding any unnecessary content.

**Comment by SoheeP** [comment]
저는 여전히 문제가 발생하고 있는데요.

vscode
버전: 1.95.3 (Universal)
커밋: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
날짜: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

monica code : v1.1.25

제안해주신 것처럼 config에 추가하였으나, 여전히 발생중입니다.

```json
{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "model": "claude-3-5-sonnet"
    },
    {
      "title": "GPT 4o",
      "model": "gpt-4o"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "강조된 코드에 대한 단위 테스트 작성"
    }
  ],
  "contextProviders": [
    {
      "name": "currentFile",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    },
    {
      "name": "url",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "선택된 코드 편집"
    },
    {
      "name": "comment",
      "description": "선택된 코드에 대한 주석 작성"
    },
    {
      "name": "share",
      "description": "현재 채팅 세션을 markdown으로 내보내기"
    },
    {
      "name": "cmd",
      "description": "쉘 명령 생성"
    },
    {
      "name": "commit",
      "description": "Git 커밋 메시지 생성"
    }
  ],
  "requestOptions": {
    "proxy": "http://127.0.0.1:7890"
  }
}
```

터미널로 통신하는 방법도 확인해봤지만, 서버에 연결할 수 없다고 합니다.

```bash
╰──➤ curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v
*   Trying 127.0.0.1:7890...
* connect to 127.0.0.1 port 7890 from 127.0.0.1 port 64113 failed: Connection refused
* Failed to connect to 127.0.0.1 port 7890 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 127.0.0.1 port 7890 after 0 ms: Couldn't connect to server 
```

그리고 애플이메일로 로그인하는데, 왜 에러 메세지는 googla auth error 인가요?

**Comment by MMMartt** [comment]
@SoheeP The above proxy settings are intended to resolve the issue of Monica being blocked (e.g., in mainland China). If you can access it normally without setting up a proxy, then the proxy is not necessary. May I ask which browser you are using to log in? Are you logging in with an email and password? If possible, providing the error from the browser's developer console would be very helpful.

**Comment by SoheeP** [comment]
@MMMartt chrome을 기본 브라우저로 사용하고 있습니다. (크롬 버전 131.0.6778.205(공식 빌드) (arm64))
모바일, 데스크탑을 두루 사용하고 싶어 애플 계정으로 연동하였고, 애플 계정으로 가입 시 private 설정을 해놨습니다.
monica 로그인 페이지에서 애플로 로그인을 선택하고, 로그인을 완료하고 나면 아래처럼 콘솔 에러가 발생합니다.

<img width="997" alt="image" src="https://github.com/user-attachments/assets/56502f12-bc6d-42d9-9e09-994f32d26143" />

**Comment by Rainboycc** [comment]
> @MMMarttchrome을 기본 브라우저로 사용하고 있습니다。 (크롬 버전 131.0.6778.205(공식 빌드) (arm64)) 모바일, 데스크탑을 두루 사용하고 싶어 애플私人的私人浴室。 莫妮卡（monica） 에러л 발생합니다。
> 
> <img alt="图像" width="997" src="https://private-user-images.githubusercontent.com/43696483/397692695-56502f12-bc6d-42d9-9e09-994f32d26143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTk1NTksIm5iZiI6MTczNTAxOTI1OSwicGF0aCI6Ii80MzY5NjQ4My8zOTc2OTI2OTUtNTY1MDJmMTItYmM2ZC00MmQ5LTllMDktOTk0ZjMyZDI2MTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA1NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOGM4MjQ3NzNlNjc2NWEyNmE1MjliYmYxNmI5ZjA3ODI5MzQ1MmY2ZDA4ZGU0ZWMyMTk1ZTJkMDJlZTAyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Wk0KOGiDJTJUs2Cb_j-EA2IEPrTE8T8Eb721hKtZC4">

我似乎遇到一样的错误

**Comment by Rainboycc** [comment]
> @SoheeP以上代理设置是为了解决Monica被封禁的问题（例如中国大陆地区），如果不设置代理就可以正常访问，那么代理就没有必要了。请问您是用什么浏览器登录的？您是用邮箱和密码登录的吗？如果可以的话，提供一下浏览器开发者控制台的错误信息会很有帮助。

我使用的是苹果账户登陆，账号是中国大陆的

**Comment by Rainboycc** [comment]
> > @SoheeP以上代理设置是为了解决Monica被封禁的问题（例如中国大陆地区），如果不设置代理就可以正常访问，那么代理就没有必要了。请问您是用什么浏览器登录的？您是用邮箱和密码登录的吗？如果可以的话，提供一下浏览器开发者控制台的错误信息会很有帮助。
> 
> 我使用的是苹果账户登陆，账号是中国大陆的

<img width="972" alt="image" src="https://github.com/user-attachments/assets/d7450ad5-bc02-4ee5-a6ec-2adba6cbcacc" />

**Comment by MMMartt** [comment]
@SoheeP This issue should now be resolved. Could you please try again? My apologies for the inconvenience.

**Comment by SoheeP** [comment]
@MMMartt 이제 로그인됩니다! 고맙습니다!
