### ISSUE TITLE
[FEATURE] Custom generate the commit message 

### ISSUE THREAD

**Issue by falan** [Monica-IM/Monica-Code#13]
## Is your feature request related to a problem?
Not applicable - This is an enhancement request.
I want to express my gratitude for your excellent work. I never expected this level of functionality from a 3rd party plugin. Great job! This is the most frequently used feature for me, whether I'm using JetBrains AI or Monica.

## Proposed Solution
Add support for customizable commit message generation through:
1. Configuration options in `config.json`
2. Add a configuration dialog to customize the commit message prompt, similar to JetBrains AI's interface

## Alternative Solutions
Currently using the `@Git Diff /commit` command, where `/commit` is followed by a custom message. After the commit message is generated, it needs to be manually copied and pasted into the commit message box.
```json
{
    "name": "commit",
    "prompt": "{{{ input }}}\n\n generate commit message using angularjs commit message format. For every file, describe the changes individually.",
    "description": "Generate a git commit message using the angularjs commit message format"
}
```

## Use Case
Enable more personalized and customized commit message generation to better match user/team preferences and requirements.

## Additional Context
No additional context provided.

## Environment (if relevant)
- IDE: PyCharm 2024.3
- Monica Code Version: 1.0.2

## Checklist

- [x] Searched for similar feature requests
- [x] Single feature scope maintained
- [x] Clear use cases provided

**Comment by MMMartt** [comment]
```
  "gitCommitPrompt": "Please write a concise and descriptive git commit message based on the following diff. The message should follow conventional commit format and be clear and informative. Here is the diff:\\n\"\"\"\\n{{diff}}\\n\"\"\"\\nCommit(Do NOT wrap with extra quotes): ",
```
You can configure this setting manually for now, as it seems that JetBrains' schema definition does not provide a prompt for it. We'll fix this issue in the next version. Currently, changes to `config.json` require restarting the IDE to take effect. However, this will be fixed in the next version. That said, the commit prompt configuration is already supported in version 1.0.2.
