### ISSUE TITLE
[BUG] Using an Apple account to authorize VS Code results in a "Google Auth Error" after logging in.

### ISSUE THREAD

**Issue by Rainboycc** [Monica-IM/Monica-Code#15]
## Bug Description

Using an Apple account to authorize VS Code results in a "Google Auth Error" after logging in.

## Environment
- IDE:  VS Code
- IDE Version:  1.96.2 (Universal)
- Monica Code Version: lastest

**Comment by Rainboycc** [comment]
My Apple account is registered in Mainland China.

**Comment by Rainboycc** [comment]
@MMMartt

**Comment by MMMartt** [comment]
@Rainboycc  This issue should now be resolved. Could you please try again? My apologies for the inconvenience.

**Comment by Rainboycc** [comment]
> @Rainboycc This issue should now be resolved. Could you please try again? My apologies for the inconvenience.

It's fine now, thank you.
