### ISSUE TITLE
[FEATURE] hopes to support customizable git commit message formats and styles

### ISSUE THREAD

**Issue by zguiyang** [Monica-IM/Monica-Code#18]
I hope there is a configuration option to control the format of git commit messages. Currently, they are all generated automatically, and I cannot submit commit messages according to team standards or personal style.

For example, I don't want it to generate detailed descriptions, add scope, etc.

<img width="530" alt="image" src="https://github.com/user-attachments/assets/02260a17-49d1-4b27-82d6-6ae508cc7086" />
<img width="539" alt="image" src="https://github.com/user-attachments/assets/7ba3a55c-c6b2-4c0c-99e8-1a018cec624e" />

**Comment by yunyuyuan** [comment]
Hello, you can customize the template "gitCommitPrompt" in `config.json`.

**Comment by zguiyang** [comment]
> Hello, you can customize the template "gitCommitPrompt" in `config.json`.

  Okay, let me give it a try.

**Comment by yunyuyuan** [comment]
@zguiyang Based on your needs, you can try this one: 
```json
"gitCommitPrompt": "Please write a concise and descriptive git commit message based on the following diff. The message should follow conventional commit format (type(scope): description) where scope indicates the affected component/module (e.g. backend, frontend, api, auth, etc). The message should be clear and informative. Here is the diff:\\n\"\"\"\\n{{diff}}\\n\"\"\"\\nCommit(Do NOT wrap with extra quotes): ",
 ```

You can click the settings button to open the configuration file.
![image](https://github.com/user-attachments/assets/d06c5cac-7549-4aaf-b08b-1c0ccf8f789d)
