### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xiemobiao** [Monica-IM/Monica-Code#2]
> ## Bug Description
> Unable to log in to the Monica plugin in Android Studio. An error message appears when attempting to log in.

> ## Environment
> - IDE: Android Studio  
> - IDE Version: Ladybug | 2024.2.1 Patch 2
> - Monica Code Version: 1.0.1
> - Operating System: Windows 11  

> ## Steps to Reproduce
> 1. Open Android Studio.  
> 2. Install the Monica plugin and attempt to log in.  
> 3. Enter valid credentials and click the login button.  

> ## Expected Behavior
> The plugin should log in successfully and display the relevant features.  

> ## Actual Behavior
> Login fails with an error message such as  "network error, connect timeout"  

> ## Screenshots
>   
![c883790b-7e1c-46f8-a9a4-403c12bb3988](https://github.com/user-attachments/assets/1d93faf6-925f-4c10-ae11-9964e88b3fc5)

> ## Additional Context
> - The network connection is stable, and other online services work fine.  
> - Restarting the IDE and reinstalling the plugin did not resolve the issue.  

> ## Checklist
> - [x] I have searched for similar issues before creating this one  
> - [x] I have provided all the requested information above  
> - [x] I can reliably reproduce this issue

**Comment by MMMartt** [comment]
It seems to be an issue with the network proxy. You can try manually specifying the proxy as outlined here: https://github.com/Monica-IM/Monica-Code/blob/main/TROUBLESHOOTING.md#network-and-proxy-issues

**Comment by MMMartt** [comment]
Let me know if it doesn't work, I'm closing this issue now.
