### ISSUE TITLE
 Login Issue with Monica Code Plugin in IntelliJ IDEA

### ISSUE THREAD

**Issue by eminem-xiao** [Monica-IM/Monica-Code#3]
Dear Monica Team,

I am a user of the Monica Unlimited plan and I am experiencing a login issue with the Monica Code plugin in IntelliJ IDEA. I have followed the troubleshooting steps from your [[official troubleshooting guide](https://github.com/Monica-IM/Monica-Code/blob/main/TROUBLESHOOTING.md)](https://github.com/Monica-IM/Monica-Code/blob/main/TROUBLESHOOTING.md), but the problem persists.

**Description of the issue:**

1. I installed the Monica Code plugin through JetBrains IDEA.
2. After clicking the login button, I was successfully redirected to the webpage and completed the login process.
3. However, the plugin in IDEA continues to show that I am not logged in.The login button remains in a loading state.

**Troubleshooting steps I have already tried:**

1. Basic troubleshooting:
   - Verified that my network connection is stable
   - Restarted IntelliJ IDEA
   - Reinstalled the Monica Code plugin
2. Following the official troubleshooting guide:
   - Attempted to configure proxy settings in `~/.monica-code/config.json`
   - Verified that my IDE version is compatible

**System Information:**

- Operating System: macOS Sequoia 15.1.1
- IDEA Version: IntelliJ IDEA 2024.3 (Ultimate Edition)
- Monica Code Plugin Version: 1.0.1

**Questions:**

1. Are there any specific proxy settings I should try for macOS Sequoia?
2. Could there be any conflict with my IDE version or macOS security settings?
3. Are there any logs I can provide to help diagnose the issue?

I would appreciate any further assistance you can provide to help resolve this login issue.

Thank you for your support!

Best regards,
Shawn

**Comment by eminem-xiao** [comment]
This is the returned error message: Something went wrong while logging in, please check your network and try again. [network error(ENOENT: no such file or directory, open)]

**Comment by eminem-xiao** [comment]
> @eminem-xiao Does the error message indicate the specific file it is attempting to access? Furthermore, could you provide details about how the settings are defined in the config.json file? With the corresponding configuration, I will attempt to reproduce the issue.@eminem-xiao 错误信息是否说明了试图访问的特定文件？此外，您能否提供有关 config.json 文件中如何定义设置的详细信息？有了相应的配置，我将尝试重现该问题。

The error message does not specify the particular file it is trying to access.
This is my complete configuration content in config.json：
{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "model": "claude-3-5-sonnet-20240620"
    },
    {
      "title": "GPT 4o",
      "model": "gpt-4o"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "currentFile",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "url",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "requestOptions": {
    "proxy": "http://127.0.0.1:7890",  
    "verifySsl": true,
    "caBundlePath": "",                     
    "clientCertificate": {                  
      "cert": "",                           
      "key": "",                            
      "passphrase": ""                      
    }
  }
}

**Comment by MMMartt** [comment]
Can you check if it work if you only preserve "proxy" line in the config? Like:
```
  "requestOptions": {
    "proxy": "http://127.0.0.1:7890/"
  }
```

**Comment by eminem-xiao** [comment]
> Can you check if it work if you only preserve "proxy" line in the config? Like:如果只保留配置中的 "proxy "行，能否正常工作？比如
> 
> ```
>   "requestOptions": {
>     "proxy": "http://127.0.0.1:7890/"
>   }
> ```

I tried it, but it still doesn't work.
Is there any issue with the configuration in IntelliJ IDEA as shown in the image below？
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/1d23ac52-5f75-4798-8e55-f8d2ec6ed24b">

**Comment by eminem-xiao** [comment]
This is the new error message after modifying the configuration when trying to log in: Something went wrong while logging in, please check your network and try again. [network error(request to https://monica.im/api/user/me failed, reason: connect ETIMEDOUT 199.59.149.205:443)]

**Comment by MMMartt** [comment]
Monica did not use the JetBrains proxy settings. Could you check the logs of your proxy software? I tested it on my end, and it seems to work fine. Here is my configuration:

```json
"requestOptions": {
    "proxy": "http://127.0.0.1:7890/"
}
```

**Comment by eminem-xiao** [comment]
I tried changing the configuration in config.json to the content you provided, but I still can't log in. Below are the logs from ~/.monica-code/logs/core.log:
<img width="1546" alt="image" src="https://github.com/user-attachments/assets/47aeac90-47ed-4674-8796-d5210942a128">

**Comment by eminem-xiao** [comment]
> I tried changing the configuration in config.json to the content you provided, but I still can't log in. Below are the logs from ~/.monica-code/logs/core.log:我尝试将 config.json 中的配置更改为您提供的内容，但仍然无法登录。以下是 ~/.monica-code/logs/core.log 中的日志： <img alt="image" width="1546" src="https://private-user-images.githubusercontent.com/50177085/391437599-47aeac90-47ed-4674-8796-d5210942a128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjI0MjAsIm5iZiI6MTczMzEyMjEyMCwicGF0aCI6Ii81MDE3NzA4NS8zOTE0Mzc1OTktNDdhZWFjOTAtNDdlZC00Njc0LTg3OTYtZDUyMTA5NDJhMTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA2NDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMWY4ZTJmZjM3MDE4ZWZmZThlNjU5NTE4NzhjODQ0NGE5Njg2NWMzMmEzNTRhZjQ1YWU0ZmM4MTU1NTNkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mRZMECf88e5d3B_rCSnRZtCXuEzfk0nQV3gBHQm8gN8">

<img width="494" alt="image" src="https://github.com/user-attachments/assets/63b450db-0692-43bc-b826-5f4e708eb8d5">

**Comment by MMMartt** [comment]
Does the proxy software generate any logs? It seems like Monica isn't using the proxy, and the DNS might be poisoned since that's not our IP. If possible, could you send me your WeChat or other contact details via email nielumartin@gmail.com? I can quickly help you identify the issue.

**Comment by eminem-xiao** [comment]
I just sent you an email.

**Comment by sun-shu** [comment]
同一个问题！

**Comment by sun-shu** [comment]
怎么解决的？

**Comment by MMMartt** [comment]
> 怎么解决的？

@sun-shu He resolved the issue using the configuration file below. Note that you may need to restart the IDE after modifying the configuration file. The current version does not handle null values in the configuration file very well, but this will be improved in future updates.
```json
{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "model": "claude-3-5-sonnet-20240620"
    },
    {
      "title": "GPT 4o",
      "model": "gpt-4o"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "currentFile",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "url",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "requestOptions": {
    "proxy": "http://127.0.0.1:7890"
  }
}
```

**Comment by sun-shu** [comment]
[2024-12-03T02:28:23] Unhandled Rejection at: [object Promise] reason: [object Object]
[2024-12-03T02:30:55] report_login_result
[2024-12-03T02:31:16] [CrepeSdk]  Unhandled api request error: /coder/issue_completion_token ApiRequestError5 0 network error(request to https://monica.im/api/coder/issue_completion_token failed, reason: connect ETIMEDOUT 199.59.149.207:443)
[2024-12-03T02:31:16] [object Object]
[2024-12-03T02:31:16] [object Object]
[2024-12-03T02:31:16] [CrepeSdk]  Unhandled api request error: /user/me ApiRequestError5 0 network error(request to https://monica.im/api/user/me failed, reason: connect ETIMEDOUT 199.59.149.207:443)
[2024-12-03T02:31:19] [CrepeSdk]  Unhandled api request error: /user_behavior/batch_create_event_v2 ApiRequestError5 0 network error(request to https://monica.im/api/user_behavior/batch_create_event_v2 failed, reason: connect ETIMEDOUT 199.59.149.207:443)
[2024-12-03T02:31:19] Unhandled Rejection at: [object Promise] reason: [object Object]


我还是不行

编辑器要设置无代理对吗

**Comment by MMMartt** [comment]
There is no need for that. The current proxy operates entirely based on the settings defined in the `config.json` file. The error indicates that the request did not go through the proxy. You might want to check the logs in your proxy software to confirm whether the request is being routed through it. If the configuration is correct, this issue should typically be resolved.

**Comment by sun-shu** [comment]
![image](https://github.com/user-attachments/assets/8177b9b2-2a90-464d-888e-475d6e95bede)
我理解应该是通过了

**Comment by sun-shu** [comment]
![image](https://github.com/user-attachments/assets/1ae4517a-da61-4477-aa38-a43c566cf03b)

**Comment by sun-shu** [comment]
可不可以帮我远程一下.....

**Comment by nasodaengineer** [comment]
Why not use the idea proxy?

**Comment by nasodaengineer** [comment]
vscode's plugins run well, but idea plugins require additional proxy configuration

**Comment by MMMartt** [comment]
Try running the command: `curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v` to see what it returns. If the response doesn't contain the correct content, please send your WeChat information to the email mentioned above. @sun-shu

**Comment by sun-shu** [comment]
![image](https://github.com/user-attachments/assets/758f5554-e1c2-4ff3-a8b9-744529d2bf17)
返回正常

**Comment by sun-shu** [comment]
我正常的monica应用和网页的插件都可以用 就是编辑器里不行

**Comment by wanghui5257** [comment]
> 我正常的monica应用和网页的插件都可以用 就是编辑器里不行

我也是这样的问题，不过我的系统mac m2

curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v
*   Trying 127.0.0.1:7890...
* Connected to 127.0.0.1 (127.0.0.1) port 7890
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Establish HTTP proxy tunnel to monica.im:443
> CONNECT monica.im:443 HTTP/1.1
> Host: monica.im:443
> User-Agent: curl/8.7.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=monica.im
*  start date: Jan 26 00:00:00 2024 GMT
*  expire date: Feb 24 23:59:59 2025 GMT
*  subjectAltName: host "monica.im" matched cert's "monica.im"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://monica.im/api/user/me
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: monica.im]
* [HTTP/2] [1] [:path: /api/user/me]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /api/user/me HTTP/2
> Host: monica.im
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 200 
< date: Wed, 04 Dec 2024 06:51:03 GMT
< content-type: application/json; charset=utf-8
< content-length: 72
< x-ratelimit-limit: 100
< x-ratelimit-remaining: 99
< x-ratelimit-reset: 60
< server: APISIX/3.2.0
< 
* Connection #0 to host 127.0.0.1 left intact
{"code":403,"msg":"permission error","error":"exceptions.UserAuthError"}%

**Comment by MMMartt** [comment]
> > 我正常的monica应用和网页的插件都可以用 就是编辑器里不行
> 
> 我也是这样的问题，不过我的系统mac m2
> 
> curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v
> 
> * Trying 127.0.0.1:7890...
> * Connected to 127.0.0.1 (127.0.0.1) port 7890
> * CONNECT tunnel: HTTP/1.1 negotiated
> * allocate connect buffer
> * Establish HTTP proxy tunnel to monica.im:443
> 
> > CONNECT monica.im:443 HTTP/1.1
> > Host: monica.im:443
> > User-Agent: curl/8.7.1
> > Proxy-Connection: Keep-Alive
> 
> < HTTP/1.1 200 Connection established <
> 
> * CONNECT phase completed
> * CONNECT tunnel established, response 200
> * ALPN: curl offers h2,http/1.1
> * (304) (OUT), TLS handshake, Client hello (1):
> * CAfile: /etc/ssl/cert.pem
> * CApath: none
> * (304) (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 / [blank] / UNDEF
> * ALPN: server accepted h2
> * Server certificate:
> * subject: CN=monica.im
> * start date: Jan 26 00:00:00 2024 GMT
> * expire date: Feb 24 23:59:59 2025 GMT
> * subjectAltName: host "monica.im" matched cert's "monica.im"
> * issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
> * SSL certificate verify ok.
> * using HTTP/2
> * [HTTP/2] [1] OPENED stream for https://monica.im/api/user/me
> * [HTTP/2] [1] [:method: GET]
> * [HTTP/2] [1] [:scheme: https]
> * [HTTP/2] [1] [:authority: monica.im]
> * [HTTP/2] [1] [:path: /api/user/me]
> * [HTTP/2] [1] [user-agent: curl/8.7.1]
> * [HTTP/2] [1] [accept: _/_]
> 
> > GET /api/user/me HTTP/2
> > Host: monica.im
> > User-Agent: curl/8.7.1
> > Accept: _/_
> 
> * Request completely sent off
>   < HTTP/2 200
>   < date: Wed, 04 Dec 2024 06:51:03 GMT
>   < content-type: application/json; charset=utf-8
>   < content-length: 72
>   < x-ratelimit-limit: 100
>   < x-ratelimit-remaining: 99
>   < x-ratelimit-reset: 60
>   < server: APISIX/3.2.0
>   <
> * Connection #0 to host 127.0.0.1 left intact
>   {"code":403,"msg":"permission error","error":"exceptions.UserAuthError"}%

@wanghui5257 Check if the Monica Code version is 1.0.1, as JetBrains only supports proxy from this version onward. The issue with the user above is due to their version being 1.0.0.

**Comment by zguiyang** [comment]
I have upgraded to the latest version and still have this problem, and I can test the API in the terminal.

terminal is also configured with http and https proxy


I use the clash verge software for proxying, and it works if I enable the **`tun`** proxy mode, but it affects my other applications.
monica code 1.0.1
macos: 15.1.1 (m3)

<img width="1008" alt="iShot_2024-12-04_22 38 41" src="https://github.com/user-attachments/assets/517daff4-fdc7-4bf3-86ec-17dab1d6b14f"> 
<img width="1018" alt="iShot_2024-12-04_22 39 10" src="https://github.com/user-attachments/assets/a49b7238-3852-43a0-8e3e-080aa5669d37">

**Comment by wanghui5257** [comment]
> > > 我正常的monica应用和网页的插件都可以用 就是编辑器里不行
> > 
> > 
> > 我也是这样的问题，不过我的系统mac m2
> > curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v
> > 
> > * Trying 127.0.0.1:7890...
> > * Connected to 127.0.0.1 (127.0.0.1) port 7890
> > * CONNECT tunnel: HTTP/1.1 negotiated
> > * allocate connect buffer
> > * Establish HTTP proxy tunnel to monica.im:443
> > 
> > > CONNECT monica.im:443 HTTP/1.1
> > > Host: monica.im:443
> > > User-Agent: curl/8.7.1
> > > Proxy-Connection: Keep-Alive
> > 
> > 
> > < HTTP/1.1 200 Connection established <
> > 
> > * CONNECT phase completed
> > * CONNECT tunnel established, response 200
> > * ALPN: curl offers h2,http/1.1
> > * (304) (OUT), TLS handshake, Client hello (1):
> > * CAfile: /etc/ssl/cert.pem
> > * CApath: none
> > * (304) (IN), TLS handshake, Server hello (2):
> > * TLSv1.2 (IN), TLS handshake, Certificate (11):
> > * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> > * TLSv1.2 (IN), TLS handshake, Server finished (14):
> > * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> > * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> > * TLSv1.2 (OUT), TLS handshake, Finished (20):
> > * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
> > * TLSv1.2 (IN), TLS handshake, Finished (20):
> > * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 / [blank] / UNDEF
> > * ALPN: server accepted h2
> > * Server certificate:
> > * subject: CN=monica.im
> > * start date: Jan 26 00:00:00 2024 GMT
> > * expire date: Feb 24 23:59:59 2025 GMT
> > * subjectAltName: host "monica.im" matched cert's "monica.im"
> > * issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
> > * SSL certificate verify ok.
> > * using HTTP/2
> > * [HTTP/2] [1] OPENED stream for https://monica.im/api/user/me
> > * [HTTP/2] [1] [:method: GET]
> > * [HTTP/2] [1] [:scheme: https]
> > * [HTTP/2] [1] [:authority: monica.im]
> > * [HTTP/2] [1] [:path: /api/user/me]
> > * [HTTP/2] [1] [user-agent: curl/8.7.1]
> > * [HTTP/2] [1] [accept: _/_]
> > 
> > > GET /api/user/me HTTP/2
> > > Host: monica.im
> > > User-Agent: curl/8.7.1
> > > Accept: _/_
> > 
> > 
> > 
> > * Request completely sent off
> >   < HTTP/2 200
> >   < date: Wed, 04 Dec 2024 06:51:03 GMT
> >   < content-type: application/json; charset=utf-8
> >   < content-length: 72
> >   < x-ratelimit-limit: 100
> >   < x-ratelimit-remaining: 99
> >   < x-ratelimit-reset: 60
> >   < server: APISIX/3.2.0
> >   <
> > * Connection #0 to host 127.0.0.1 left intact
> >   {"code":403,"msg":"permission error","error":"exceptions.UserAuthError"}%
> 
> @wanghui5257 Check if the Monica Code version is 1.0.1, as JetBrains only supports proxy from this version onward. The issue with the user above is due to their version being 1.0.0.

<img width="858" alt="image" src="https://github.com/user-attachments/assets/ca7fd39f-284a-4274-9b02-6be756592bc8">
用的版本是1.0.1

**Comment by MMMartt** [comment]
@wanghui5257 Please refer to https://github.com/Monica-IM/Monica-Code/issues/3#issuecomment-2519364755 proper settings should make proxy work.

**Comment by wanghui5257** [comment]
> curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v

curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v
*   Trying 127.0.0.1:7890...
* Connected to 127.0.0.1 (127.0.0.1) port 7890
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Establish HTTP proxy tunnel to monica.im:443
> CONNECT monica.im:443 HTTP/1.1
> Host: monica.im:443
> User-Agent: curl/8.7.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=monica.im
*  start date: Aug  7 00:00:00 2024 GMT
*  expire date: Sep  6 23:59:59 2025 GMT
*  subjectAltName: host "monica.im" matched cert's "monica.im"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M03
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://monica.im/api/user/me
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: monica.im]
* [HTTP/2] [1] [:path: /api/user/me]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /api/user/me HTTP/2
> Host: monica.im
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 200 
< content-type: application/json; charset=utf-8
< content-length: 72
< date: Thu, 05 Dec 2024 06:56:46 GMT
< server: APISIX/3.2.0
< x-ratelimit-limit: 10000
< x-ratelimit-remaining: 9999
< x-ratelimit-reset: 60
< x-cache: Miss from cloudfront
< via: 1.1 061125c15858f6df0c7188ff78a179ce.cloudfront.net (CloudFront)
< x-amz-cf-pop: HKG54-P2
< x-amz-cf-id: FY8SGG8NcLu2ftOU26aEWElkOcrF0t3CX4ubR3djJd8cE_yH34eQZQ==
< 
* Connection #0 to host 127.0.0.1 left intact
{"code":403,"msg":"permission error","error":"exceptions.UserAuthError"}%

**Comment by wanghui5257** [comment]
When will it be resolved?

**Comment by MMMartt** [comment]
> When will it be resolved?

This issue has already been resolved. Take a closer look at the discussion in the issue thread—everyone managed to fix it by properly configuring the `config.json`.

**Comment by pteric** [comment]
![image](https://github.com/user-attachments/assets/8936e5c7-d2e7-4a8e-9ac5-23a3ee24fc79)
![image](https://github.com/user-attachments/assets/33c00a6e-bde2-4d89-8fe4-c5836267f174)

我这里目前在 Goland 上使用 monica 1.0.2 版本插件，如上图已经设置了 config.json 文件，通过 apple 登录依然登录失败，并且第一次的登录总是会提示 Google Auth Error（如上图），请问怎么解决？

**Comment by MMMartt** [comment]
@pteric Could you provide the error message from the login page console? It seems to be a different issue compared to the one mentioned earlier. Additionally, could you try using a different browser to see if the issue persists?

**Comment by pteric** [comment]
![image](https://github.com/user-attachments/assets/ee989a17-5697-48f3-b358-b55c0cbad6d1)
![image](https://github.com/user-attachments/assets/c1b9d222-7f70-4229-b14f-37195578af34)
![image](https://github.com/user-attachments/assets/ff0e9530-b2e4-4680-9a95-f25845ef9d52)

Goland 里插件的登录页面没有报错提醒，只是在不停的转圈 loading 状态，然后截图了一些登录时 chrome console 的报错信息，不知道可不可以用的上

此外，我执行 curl -x http://127.0.0.1:7890 https://monica.im/api/user/me -v 发现连不通，和上面反馈的现象不太一样
![image](https://github.com/user-attachments/assets/e048057b-1674-4119-8421-5f95ffd79293)

**Comment by RabbitCocoa** [comment]
从日志中我观察到 我尝试访问74.86.151.167这个ip地址 
[2024-12-20T06:38:31] [CrepeSdk]  Unhandled api request error: /user/me ApiRequestError5 0 network error(request to https://monica.im/api/user/me failed, reason: connect ETIMEDOUT 74.86.151.167:443)
我尝试用ping该地址超时
这需要我怎么做呢

**Comment by RabbitCocoa** [comment]
我成功了 
通过浏览器访问https://monica.im/api/user/me 
![image](https://github.com/user-attachments/assets/a45ec50d-76de-43d2-85ea-99b10c088119)
将远程地址填到proxy的代理即可

**Comment by Rainboycc** [comment]
我想要给vscode插件授权，我用苹果账号登陆的显示google auth error，无法授权，我用google账号可以正常授权，但是我的会员是在苹果账户上购买的，我希望能够享受到我的权益

**Comment by MMMartt** [comment]
@pteric @Rainboycc @Rainboycc  This issue should now be resolved. Could you please try again? My apologies for the inconvenience.

**Comment by ihzhatamamy** [comment]
Hi Monica Team,

why my code codebase indexing stuck in initializing?

![Image](https://github.com/user-attachments/assets/80c6cc52-055b-4534-b3a7-e9e0b1dfa8dc)

i need that feature because to give a context when i'm asking. thanks
