### ISSUE TITLE
[BUG] CPU usage reaches 100% in the VS Code IDE.

### ISSUE THREAD

**Issue by zhenghao21** [Monica-IM/Monica-Code#5]
## Bug Description
The CPU usage reaches 100%.
## Environment
- IDE: VS Code
- IDE Version: 1.95.3
- Monica Code Version: 1.1.22
- Operating System:  Windows 11,

## Screenshots
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/c5acb7f9-7373-408f-bfb7-8c0fee888f4b">

## Additional Context
When I open VS Code and do nothing, the CPU usage reaches 100%. Then, I used the binary method to filter the extensions and found that when I disabled the Monica extension, the CPU usage dropped to a normal level. I wonder if this issue only happens to me?

**Comment by MMMartt** [comment]
This is because Monica Code embeds the codebase locally, cpu usage would drop after this finish. You can set `disableIndexing` to `true` in the `config.json` file to disable this.

**Comment by zhenghao21** [comment]
> This is because Monica Code embeds the codebase locally, cpu usage would drop after this finish. You can set `disableIndexing` to `true` in the `config.json` file to disable this.这是因为 Monica Code 将代码库嵌入本地，完成后 CPU 使用率会下降。您可以在 `disableIndexing` 文件中将 `true` 设置为 `config.json` 以禁用此功能。
> 
> Running embedding locally is unavoidable and consumes CPU resources (since it's not feasible to quietly send the code to our servers), we can later explore ways to optimize this experience.本地运行嵌入是不可避免的，并且消耗 CPU 资源（因为将代码安静地发送到我们的服务器是不可行的），我们可以稍后探索优化此体验的方法。

**Comment by zhenghao21** [comment]
> This is because Monica Code embeds the codebase locally, cpu usage would drop after this finish. You can set `disableIndexing` to `true` in the `config.json` file to disable this.这是因为 Monica Code 将代码库嵌入本地，完成后 CPU 使用率会下降。您可以在 `disableIndexing` 文件中将 `true` 设置为 `config.json` 以禁用此功能。
> 
> Running embedding locally is unavoidable and consumes CPU resources (since it's not feasible to quietly send the code to our servers), we can later explore ways to optimize this experience.本地运行嵌入是不可避免的，并且消耗 CPU 资源（因为将代码安静地发送到我们的服务器是不可行的），我们可以稍后探索优化此体验的方法。

Thanks! This information is very helpful to me.
