### ISSUE TITLE
1.0.1 version cannot be used in jetbrains

### ISSUE THREAD

**Issue by zguiyang** [Monica-IM/Monica-Code#7]
I have upgraded to the latest version, but I still have this issue. I tested the API link in the terminal, and it was successful, but accessing it in the app still fails.

terminal is also configured with http and https proxy

I use the clash verge software for proxying, and it works if I enable the **`tun`** proxy mode, but it affects my other applications.
monica code 1.0.1
macos: 15.1.1 (m3)

<img width="1008" alt="iShot_2024-12-04_22 38 41" src="https://github.com/user-attachments/assets/517daff4-fdc7-4bf3-86ec-17dab1d6b14f"> 
<img width="1018" alt="iShot_2024-12-04_22 39 10" src="https://github.com/user-attachments/assets/a49b7238-3852-43a0-8e3e-080aa5669d37">

_Originally posted by @zguiyang in https://github.com/Monica-IM/Monica-Code/issues/3#issuecomment-2517633808_

**Comment by MMMartt** [comment]
```
{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "model": "claude-3-5-sonnet-20240620"
    },
    {
      "title": "GPT 4o",
      "model": "gpt-4o"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "currentFile",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "url",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "requestOptions": {
    "proxy": "http://127.0.0.1:7890"
  }
}
```

The proxy settings in the IDE and the plugin's proxy settings are not interconnected. Based on our tests, configuring the `~/.monica-code/config.json` file as outlined above should enable the proxy functionality. A restart of the IDE might be necessary for the changes to take effect. Could you please double-check this? In previous cases where network issues occurred, the problems were either due to incorrect plugin versions or misconfigurations. Once corrected, everything worked as expected. If the issue persists, we can take a closer look later.

**Comment by zguiyang** [comment]
has been resolved, but the following configuration is still needed in ~/.monica-code/config.json

```
  "requestOptions": {
    "proxy": "http://127.0.0.1:7890/"
  }
```

**Comment by zguiyang** [comment]
> ```
> {
>   "models": [
>     {
>       "title": "Claude 3.5 Sonnet",
>       "model": "claude-3-5-sonnet-20240620"
>     },
>     {
>       "title": "GPT 4o",
>       "model": "gpt-4o"
>     }
>   ],
>   "customCommands": [
>     {
>       "name": "test",
>       "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
>       "description": "Write unit tests for highlighted code"
>     }
>   ],
>   "contextProviders": [
>     {
>       "name": "currentFile",
>       "params": {}
>     },
>     {
>       "name": "diff",
>       "params": {}
>     },
>     {
>       "name": "terminal",
>       "params": {}
>     },
>     {
>       "name": "problems",
>       "params": {}
>     },
>     {
>       "name": "url",
>       "params": {}
>     }
>   ],
>   "slashCommands": [
>     {
>       "name": "edit",
>       "description": "Edit selected code"
>     },
>     {
>       "name": "comment",
>       "description": "Write comments for the selected code"
>     },
>     {
>       "name": "share",
>       "description": "Export the current chat session to markdown"
>     },
>     {
>       "name": "cmd",
>       "description": "Generate a shell command"
>     },
>     {
>       "name": "commit",
>       "description": "Generate a git commit message"
>     }
>   ],
>   "requestOptions": {
>     "proxy": "http://127.0.0.1:7890"
>   }
> }
> ```
> 
> The proxy settings in the IDE and the plugin's proxy settings are not interconnected. Based on our tests, configuring the `~/.monica-code/config.json` file as outlined above should enable the proxy functionality. A restart of the IDE might be necessary for the changes to take effect. Could you please double-check this? In previous cases where network issues occurred, the problems were either due to incorrect plugin versions or misconfigurations. Once corrected, everything worked as expected. If the issue persists, we can take a closer look later.

Thank you very much, it can be used now

**Comment by MMMartt** [comment]
Thank you for your report. We may add a proxy option directly in the IDE settings in the next version and ensure it can be tested through the UI. Many users have indeed encountered this issue.
