### ISSUE TITLE
[BUG] Unable to use, connection timed out   

### ISSUE THREAD

**Issue by asasas234** [Monica-IM/Monica-Code#9]
![image](https://github.com/user-attachments/assets/fbf29cec-4957-4bc3-b409-dcc643dc9844)

**Comment by asasas234** [comment]
@MMMartt Please take a look at my question.

**Comment by MMMartt** [comment]
Check out the content in these two issues. The people experiencing problems were able to log in normally using the correct `config.json` and plugin versions: https://github.com/Monica-IM/Monica-Code/issues/7 https://github.com/Monica-IM/Monica-Code/issues/3

**Comment by asasas234** [comment]
> Check out the content in these two issues. The people experiencing problems were able to log in normally using the correct `config.json` and plugin versions: #7 #3

Thank you for letting me know it's resolved.
